name: go2_multi_agent_bridge
from_domain: 0
to_domain: 40
topics:
  /multi_agent/agents/go2/state:
    type: multi_agent_msgs/msg/AgentState
  /multi_agent/agents/ranger/state:
    type: multi_agent_msgs/msg/AgentState
    reversed: true
